spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music-platform
    username: postgres
    password: g12nokona
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB

minio:
  url:
    http://localhost:9000
  bucket:
    name:
      tinkoff-music
  access:
    key:
      zhurkin
    secret:
      g12nokona

logging:
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    web: trace
  file:
    name: application-debug.log

